appname = sensors
httpport = 8081
runmode = prod
autorender = false
copyrequestbody = true
EnableDocs = false
license_binary_path = ./binaries/sensors-payload-decoder
license_timeout_seconds = 10
ignore_urls = /,/sensors/send

[prod]
redisHostAdmin = redis:6379
redisPwdAdmin =
redisAdminType = node
ckHost = clickhouse:9000
ckUsername = default
ckDatabase = sensors
ckPwd =
