appname = sensors
httpport = 8082
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
# payload 许可证路径
license_binary_path = ./binaries/sensors-payload-license
# 单次许可证处理最长执行时间（秒）
license_timeout_seconds = 10
#忽略URL
ignore_urls = /,/sensors/send

[dev]
#redis
#admin实例
redisHostAdmin = 127.0.0.1:6379
redisPwdAdmin =
redisAdminType = node

#clickhouse
ckHost = 127.0.0.1:9000
ckUsername = default
ckDatabase = sensors
ckPwd =
